### ISSUE TITLE
0.9.1 and Java 7

### ISSUE THREAD

**Issue by cmonty** [oedura/scavro#3]
I'm having trouble using the newly released 0.9.1 with Java 7 (and Scala 11). Looking at the stack trace it appears 0.9.1 might have been compiled with a different version of Java than 0.9.0.

In my `plugins.sbt`:

``` scala
addSbtPlugin("org.oedura" % "scavro" % "0.9.1") 
```

Running `sbt compile` I receive:

```
java.lang.UnsupportedClassVersionError: org/oedura/scavro/plugin/NullOutputStream : Unsupported major.minor version 52.0              
        at java.lang.ClassLoader.defineClass1(Native Method)                                                                          
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)                                                                    
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)                                                    
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)                                                               
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)                                                                 
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)                                                                     
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)                                                                     
        at java.security.AccessController.doPrivileged(Native Method)                                                                 
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)                                                                 
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)                                                                      
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)                                                                      
        at org.oedura.scavro.plugin.AvroCodegen.outputStream(AvroCodegen.scala:26)                                                    
        at org.oedura.scavro.plugin.AvroCodegen.runTool(AvroCodegen.scala:31)                                                         
        at org.oedura.scavro.plugin.AvroCodegen.compileSchema(AvroCodegen.scala:50)                                                   
        at org.oedura.scavro.plugin.AvroCodegen.run(AvroCodegen.scala:21)                                                             
        at org.oedura.scavro.plugin.AvroCodegenPlugin$autoImport$$anonfun$baseAvroCodegenSettings$6.apply(AvroCodegenPlugin.scala:29) 
        at org.oedura.scavro.plugin.AvroCodegenPlugin$autoImport$$anonfun$baseAvroCodegenSettings$6.apply(AvroCodegenPlugin.scala:26) 
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)                                                               
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)                                                         
        at sbt.std.Transform$$anon$4.work(System.scala:63)                                                                            
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)                                                    
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)                                                    
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)                                                                     
        at sbt.Execute.work(Execute.scala:235)                                                                                        
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)                                                                     
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)                                                                     
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)                                      
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)                                                             
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)                                                                   
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)                                                    
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)                                                                   
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)                                            
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)                                            
        at java.lang.Thread.run(Thread.java:745)                                                                                      
```

Is this intended with 0.9.1?

**Comment by BrianLondon** [comment]
That's certainly not desired. Do you get the same thing with 1.0.0?

**Comment by cmonty** [comment]
Same error.

I changed my `plugins.sbt` to:

``` scala
addSbtPlugin("org.oedura" % "scavro-plugin" % "1.0.0")
```

**Comment by BrianLondon** [comment]
Ok, thanks.  It's probably going to be a cross compiler setting in the scavro sbt file.  I'll take a look.

**Comment by cmonty** [comment]
Thanks! I should add that I was able to get the plugin working with Java 8, however we are pinned to Java 7 for a little while more.

**Comment by BrianLondon** [comment]
Can you try again please with version `1.0.1-SNAPSHOT`?  If that works I'll do a signed release.  You may need to add the following line to your build.sbt and plugins.sbt files:

``` scala
resolvers += Resolver.sonatypeRepo("snapshots")
```

**Comment by cmonty** [comment]
Hmm. I'm still receiving the same error with

``` scala
addSbtPlugin("org.oedura" % "scavro-plugin" % "1.0.1-SNAPSHOT")
```

**Comment by cmonty** [comment]
Just in case this helps, the Java version I'm using:

```
java version "1.7.0_65"                                          
OpenJDK Runtime Environment (IcedTea 2.5.1) (7u65-2.5.1-2~deb7u1)
OpenJDK 64-Bit Server VM (build 24.65-b04, mixed mode)           
```

**Comment by BrianLondon** [comment]
Ok, I was able to reproduce your issue with the following java version

```
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)
```

I recompiled another snapshot and was able to get it working on java 7 with the following `plugins.sbt` file.

``` scala
resolvers += Resolver.sonatypeRepo("snapshots")
addSbtPlugin("org.oedura" % "scavro-plugin" % "1.0.1-SNAPSHOT")
```

Can you please try that now?  If it works I'll put out a release.  Note that you may need to clear your local ivy cache.

**Comment by BrianLondon** [comment]
@cmonty bump

**Comment by cmonty** [comment]
@BrianLondon Sorry! I'll try to test this in the next few hours.

**Comment by BrianLondon** [comment]
Cool, thanks.  Please remember to clear your ivy cache.

**Comment by cmonty** [comment]
:+1: Works for me on Java 7 now.

**Comment by BrianLondon** [comment]
Great.  Deployed to central as 1.0.1.
